version: '3'

services:
  app:
    build:
      context: ./app/
      dockerfile: Dockerfile
    image: go-app
    container_name: go-app
    ports:
      - 8080:80
    volumes:
      - ./app:/usr/src/app/stady-go-echo:cached
    tty: true
    command: /bin/sh -c "while sleep 1000; do :; done"
